src/Admin.Web/Pages/CreateUser.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Admin.Web.Domain;
using Admin.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Yes.Infrastructure.Common.Extensions;

namespace Admin.Web.Pages
{
    public class CreateUserModel : PageModel
    {
        private readonly ILogger<CreateUserModel> logger;
        private readonly IApplicationUserManager userManager;
        
        public CreateUserModel(ILogger<CreateUserModel> logger, IApplicationUserManager userManager)
        {
            this.logger = logger;
            this.userManager = userManager;
        }
        
        [BindProperty]
        public UserFormModel Input { get; set; }

        
        public class UserFormModel
        {
            [Required(ErrorMessage = "Поле обязательно для заполнения")]
            [Display(Name = "Имя пользователя")]
            public string UserName { get; set; }
                
            [Required]
            [StringLength(100, ErrorMessage = "Длинна пароля должна быть не менее {2} символов", MinimumLength = 5)]
            [DataType(DataType.Password)]
            [Display(Name = "Пароль")]
            public string Password { get; set; }
    
            [DataType(DataType.Password)]
            [Display(Name = "Подтверждение пароля")]
            [Compare("Password", ErrorMessage = "Значения паролей не совпадают")]
            public string ConfirmPassword { get; set; }
                
            [Required(ErrorMessage = "Поле обязательно для заполнения")]
            [Display(Name = "ФИО")]
            public string Name { get; set; }
                
            [Required(ErrorMessage = "Поле обязательно для заполнения")]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }
                
            [Required(ErrorMessage = "Поле обязательно для заполнения")]
            [Display(Name = "Роль")]
            public string Role { get; set; }
        }
        
        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    UserName = Input.UserName, 
                    Email = Input.Email,
                    Name = Input.Name
                };
                var result = await userManager.CreateAsync(user, Input.Password);
                if (result.Succeeded)
                {
                    logger.LogInformation($"User successfully created. User: {user.ToJsonString()}");
                    await userManager.AddToRoleAsync(user, Input.Role);

                    return RedirectToPage("/Users");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            return Page();
        }
    }
}

src/Admin.Web/Pages/CreditApplicationEdit.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Yes.CreditApplication.Api.Client;
using Yes.CreditApplication.Api.Contracts.Admin;
using Yes.CreditApplication.Api.Contracts.Enums;
using Yes.Infrastructure.Common.Extensions;

namespace Admin.Web.Pages
{
    public class CreditApplicationEdit : PageModel
    {
        private readonly ILogger<CreditApplicationEdit> logger;
        private readonly IAdminCreditApplicationClient client;
        
        public CreditApplicationEdit(ILogger<CreditApplicationEdit> logger, IAdminCreditApplicationClient client)
        {
            this.logger = logger;
            this.client = client;
        }
        
        [BindProperty]
        public CreditApplicationEditViewModel CreditApplication { get; set; }
        
        public async Task<IActionResult> OnGetAsync(Guid creditApplicationId)
        {
            var response = await client.GetCreditApplicationEditViewModel(creditApplicationId);
            if (response.IsSuccessStatusCode)
            {
                if (response.Content.Status != CreditApplicationStatus.InProgress)
                {
                    return new RedirectToPageResult("/CreditApplication", new {creditApplicationId});
                }
                CreditApplication = response.Content;
            }
            return Page();
        }
        
        public async Task<IActionResult> OnPostAsync(Guid creditApplicationId)
        {
            var beginTime = DateTime.Now;
            try
            {
                var response = await client.UpdateCreditApplication(creditApplicationId, CreditApplication);
                if (!response.IsSuccessStatusCode)
                    return Page();
                return new RedirectToPageResult("/CreditApplication", new {creditApplicationId});
            }
            catch (Exception e)
            {
                logger.LogError(e, $"Error while updating credit application. Duration: {beginTime.GetDuration()} CreditApplicationId: {creditApplicationId}, Request: {CreditApplication}");
                return Page();
            }
        }
    }
}

src/Admin.Web/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Admin.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/Admin.Web/Pages/ForgotPassword.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Admin.Web.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;

namespace Admin.Web.Pages
{
    public class ForgotPasswordModel : PageModel
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IEmailSender emailSender;

        public ForgotPasswordModel(UserManager<ApplicationUser> userManager, IEmailSender emailSender)
        {
            this.userManager = userManager;
            this.emailSender = emailSender;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.FindByEmailAsync(Input.Email);
                if (user == null || !(await userManager.IsEmailConfirmedAsync(user)))
                {
                    // Don't reveal that the user does not exist or is not confirmed
                    return RedirectToPage("./ForgotPasswordConfirmation");
                }

                // For more information on how to enable account confirmation and password reset please 
                // visit https://go.microsoft.com/fwlink/?LinkID=532713
                var code = await userManager.GeneratePasswordResetTokenAsync(user);
                code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                var callbackUrl = Url.Page(
                    "/Account/ResetPassword",
                    pageHandler: null,
                    values: new { area = "Identity", code },
                    protocol: Request.Scheme);

                await emailSender.SendEmailAsync(
                    Input.Email,
                    "Reset Password",
                    $"Please reset your password by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

                return RedirectToPage("./ForgotPasswordConfirmation");
            }

            return Page();
        }
    }
}

src/Admin.Web/Pages/ForgotPasswordConfirmation.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Admin.Web.Pages
{
    [AllowAnonymous]
    public class ForgotPasswordConfirmation : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/Admin.Web/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Admin.Web.Domain.FileBuilders;
using Admin.Web.Extensions;
using Admin.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Yes.CreditApplication.Api.Client;
using Yes.CreditApplication.Api.Contracts.Admin;
using Yes.CreditApplication.Api.Contracts.Enums;
using Yes.Infrastructure.Common.Extensions;

namespace Admin.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> logger;
        private readonly IAdminCreditApplicationClient client;
        private readonly IFileBuilder fileBuilder;
        
        public IndexModel(ILogger<IndexModel> logger, IAdminCreditApplicationClient client, IFileBuilder fileBuilder, ApplicationConfiguration configuration)
        {
            this.logger = logger;
            this.client = client;
            this.fileBuilder = fileBuilder;
            PageSize = configuration.PageSize;
        }
        
        [BindProperty(SupportsGet = true)]
        public int PageNumber { get; set; }
        
        [BindProperty(SupportsGet = true)]
        public string DateFrom { get; set; }
        
        [BindProperty(SupportsGet = true)]
        public string DateTo { get; set; }
        
        [BindProperty(SupportsGet = true)]
        public string DateOfBirth { get; set; }
        
        [BindProperty(SupportsGet = true)]
        public string PhoneNumber { get; set; }
        
        [BindProperty(SupportsGet = true)]
        public string LastName { get; set; }
        
        [BindProperty(SupportsGet = true)]
        public string FirstName { get; set; }
        
        [BindProperty(SupportsGet = true)]
        public string MiddleName { get; set; }
        
        [BindProperty(SupportsGet = true)]
        public List<int> Statuses { get; set; }
        
        [BindProperty(SupportsGet = true)]
        public List<int> ProfileTypes { get; set; }
        
        public long Total { get; set; }
        public int PageSize { get; }
        public int TotalPages => (int)Math.Ceiling(decimal.Divide(Total, PageSize));
        public bool PreviousButtonEnabled => PageNumber > 1;
        public bool NextButtonEnabled => PageNumber < TotalPages;
        
        public List<CreditApplicationListItemModel> CreditApplications { get; set; }
        
        public async Task OnGetAsync()
        {
            DateFrom = DateTime.Today.ToDateFormat();
            await OnGetSearchAsync();
        }

        public async Task OnGetSearchAsync()
        {
            var beginTime = DateTime.Now;
            try
            {
                if (PageNumber <= 0)
                    PageNumber = 1;
                if (Statuses.Contains(0))
                    Statuses = new List<int>();
                if (ProfileTypes.Contains(0))
                    ProfileTypes = new List<int>();
                var request = new CreditApplicationListFilterModel
                {
                    Take = PageSize,
                    Skip = PageSize * (PageNumber - 1),
                    DateFrom = getDate(DateFrom),
                    DateTo = getDate(DateTo),
                    DateOfBirth = getDate(DateOfBirth),
                    Statuses = Statuses.Select(x => (CreditApplicationStatus)x).ToList(),
                    ProfileTypes = ProfileTypes.Select(x => (ProfileType)x).ToList(),
                    LastName = LastName,
                    FirstName = FirstName,
                    MiddleName = MiddleName,
                    PhoneNumber = PhoneNumber
                };
                var response = await client.GetCreditApplications(request);
                if (response.IsSuccessStatusCode)
                {
                    CreditApplications = response.Content.Items;
                    Total = response.Content.Total;    
                }
                else
                {
                    logger.LogError($"Error while getting credit applications. Duration: {beginTime.GetDuration()} Request: {request}, ErrorMessage: {response.ErrorMessage}");   
                }
            }
            catch (Exception e)
            {
                logger.LogError(e, $"Error while getting credit applications. Duration: {beginTime.GetDuration()}");
            }
        }

        public async Task<IActionResult> OnGetExportCsvAsync()
        {
            return await onGetExportAsync(FileType.Csv);
        }

        public async Task<IActionResult> OnGetExportExcelAsync()
        {
            return await onGetExportAsync(FileType.Excel);
        }

        private async Task<IActionResult> onGetExportAsync(FileType fileType)
        {
            var beginTime = DateTime.Now;
            try
            {
                if (Statuses.Contains(0))
                    Statuses = new List<int>();
                if (ProfileTypes.Contains(0))
                    ProfileTypes = new List<int>();
                var request = new CreditApplicationListFilterModel
                {
                    DateFrom = getDate(DateFrom),
                    DateTo = getDate(DateTo),
                    DateOfBirth = getDate(DateOfBirth),
                    Statuses = Statuses.Select(x => (CreditApplicationStatus)x).ToList(),
                    ProfileTypes = ProfileTypes.Select(x => (ProfileType)x).ToList(),
                    LastName = LastName,
                    FirstName = FirstName,
                    MiddleName = MiddleName,
                    PhoneNumber = PhoneNumber
                };
                var response = await client.GetCreditApplicationsForExport(request);
                if (response.IsSuccessStatusCode)
                {
                    var fileStream = fileBuilder.BuildFile(fileType, response.Content);
                    return fileType == FileType.Csv
                        ? File(fileStream, "text/csv", $"CreditApplications-{DateTime.Now.ToSqlFormat()}.csv")
                        : File(fileStream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", $"CreditApplications-{DateTime.Now.ToSqlFormat()}.xlsx");
                }

                logger.LogError($"Error while getting credit applications for export. Duration: {beginTime.GetDuration()} Request: {request}, ErrorMessage: {response.ErrorMessage}");
                return new StatusCodeResult((int)HttpStatusCode.InternalServerError);
            }
            catch (Exception e)
            {
                logger.LogError(e, $"Error while creating credit applications excel file. Duration: {beginTime.GetDuration()}");
                return new StatusCodeResult((int)HttpStatusCode.InternalServerError);
            }
        }

        private DateTime? getDate(string date)
        {
            return string.IsNullOrWhiteSpace(date)
                ? default(DateTime?)
                : DateTime.ParseExact(date,"dd.MM.yyyy", CultureInfo.InvariantCulture);
        }
    }
}

src/Admin.Web/Pages/Logout.cshtml.cs
using System.Threading.Tasks;
using Admin.Web.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Admin.Web.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly ILogger<LogoutModel> logger;
        private readonly SignInManager<ApplicationUser> signInManager;
        

        public LogoutModel(ILogger<LogoutModel> logger, SignInManager<ApplicationUser> signInManager)
        {
            this.signInManager = signInManager;
            this.logger = logger;
        }

        public async Task<IActionResult> OnPost()
        {
            await signInManager.SignOutAsync();
            logger.LogInformation("User logged out.");
            return RedirectToPage();
        }
    }
}

src/Admin.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Admin.Web.Pages
{
    [Authorize(Roles = "Admin")]
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

src/Admin.Web/Pages/ForgotPassword.cshtml
@page
@model ForgotPasswordModel
@{
    ViewData["Title"] = "Забыли пароль?";
}
<h1>@ViewData["Title"]</h1>
<h4>Введите свой email.</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Input.Email"></label>
                <input asp-for="Input.Email" class="form-control" />
                <span asp-validation-for="Input.Email" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/Admin.Web/Pages/Index.cshtml
@page "{handler?}"
@using Admin.Web.Domain.FileBuilders
@using Admin.Web.Extensions
@using Yes.CreditApplication.Api.Contracts.Enums
@using Yes.Infrastructure.Common.Extensions
@model IndexModel
@{
    ViewData["Title"] = "Заявки на кредит";
}


<form id="filtersForm" method="get" autocomplete="off">
    <div class="form-row">
        <div class="form-group date col">
            <input type="text" class="form-control" name="dateFrom" value="@Model.DateFrom" placeholder="Дата с">
        </div>
        <div class="form-group date col">
            <input type="text" class="form-control" name="dateTo" value="@Model.DateTo" placeholder="Дата по">
        </div>
        <div class="form-group col">
            <input type="text" class="form-control" name="lastName" value="@Model.LastName" placeholder="Фамилия" >
        </div>
        <div class="form-group col">
            <input type="text" class="form-control" name="firstName" value="@Model.FirstName" placeholder="Имя">
        </div>
        <div class="form-group col">
            <input type="text" class="form-control" name="middleName" value="@Model.MiddleName" placeholder="Отчество">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group date col">
            <input type="text" class="form-control" name="dateOfBirth" value="@Model.DateOfBirth" placeholder="Дата рождения">
        </div>
        <div class="form-group col">
            <input type="text" class="form-control" name="phoneNumber" value="@Model.PhoneNumber" placeholder="Номер телефона (79999999999)">
        </div>
        <div class="form-group col">
            <select class="form-control custom-select" name="statuses" id="statusSelect" multiple="multiple">
                <option value="@((int)CreditApplicationStatus.Draft)" selected="@Model.Statuses.Contains((int)CreditApplicationStatus.Draft)">@CreditApplicationStatus.Draft.GetDescription()</option>
                <option value="@((int)CreditApplicationStatus.New)" selected="@Model.Statuses.Contains((int)CreditApplicationStatus.New)">@CreditApplicationStatus.New.GetDescription()</option>
                <option value="@((int)CreditApplicationStatus.InProgress)" selected="@Model.Statuses.Contains((int)CreditApplicationStatus.InProgress)">@CreditApplicationStatus.InProgress.GetDescription()</option>
                <option value="@((int)CreditApplicationStatus.UnableToContact)" selected="@Model.Statuses.Contains((int)CreditApplicationStatus.UnableToContact)">@CreditApplicationStatus.UnableToContact.GetDescription()</option>
                <option value="@((int)CreditApplicationStatus.UnableToContactArchive)" selected="@Model.Statuses.Contains((int)CreditApplicationStatus.UnableToContactArchive)">@CreditApplicationStatus.UnableToContactArchive.GetDescription()</option>
                <option value="@((int)CreditApplicationStatus.Processed)" selected="@Model.Statuses.Contains((int)CreditApplicationStatus.Processed)">@CreditApplicationStatus.Processed.GetDescription()</option>
                <option value="@((int)CreditApplicationStatus.Rejected)" selected="@Model.Statuses.Contains((int)CreditApplicationStatus.Rejected)">@CreditApplicationStatus.Rejected.GetDescription()</option>
                <option value="@((int)CreditApplicationStatus.ClientRejected)" selected="@Model.Statuses.Contains((int)CreditApplicationStatus.ClientRejected)">@CreditApplicationStatus.ClientRejected.GetDescription()</option>
                <option value="@((int)CreditApplicationStatus.NeedToCallBack)" selected="@Model.Statuses.Contains((int)CreditApplicationStatus.NeedToCallBack)">@CreditApplicationStatus.NeedToCallBack.GetDescription()</option>
                <option value="@((int)CreditApplicationStatus.TechnicalProblem)" selected="@Model.Statuses.Contains((int)CreditApplicationStatus.TechnicalProblem)">@CreditApplicationStatus.TechnicalProblem.GetDescription()</option>
            </select>
        </div>
        <div class="form-group col">
            <select class="form-control custom-select" name="profileTypes" id="profileTypeSelect" multiple="multiple">
                <option value="@((int)ProfileType.Full)" selected="@Model.ProfileTypes.Contains((int)ProfileType.Full)">@ProfileType.Full.GetDescription()</option>
                <option value="@((int)ProfileType.Medium)" selected="@Model.ProfileTypes.Contains((int)ProfileType.Medium)">@ProfileType.Medium.GetDescription()</option>
                <option value="@((int)ProfileType.Short)" selected="@Model.ProfileTypes.Contains((int)ProfileType.Short)">@ProfileType.Short.GetDescription()</option>
            </select>
        </div>
        <div class="form-group col text-right">
            <div class="btn-group">
                <button type="submit" class="btn btn-primary mb-2" asp-page-handler="Search">
                    <svg style="margin-top: -3px; margin-right: 1px;" class="bi bi-search" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 011.415 0l3.85 3.85a1 1 0 01-1.414 1.415l-3.85-3.85a1 1 0 010-1.415z" clip-rule="evenodd"/>
                        <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 100-11 5.5 5.5 0 000 11zM13 6.5a6.5 6.5 0 11-13 0 6.5 6.5 0 0113 0z" clip-rule="evenodd"/>
                    </svg> Найти
                </button>
                <button type="button" class="btn btn-primary mb-2 dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <button class="dropdown-item" type="submit" asp-page-handler="ExportCsv">
                       <svg class="bi bi-file-text" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                         <path fill-rule="evenodd" d="M4 1h8a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2zm0 1a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1H4z"/>
                         <path fill-rule="evenodd" d="M4.5 10.5A.5.5 0 0 1 5 10h3a.5.5 0 0 1 0 1H5a.5.5 0 0 1-.5-.5zm0-2A.5.5 0 0 1 5 8h6a.5.5 0 0 1 0 1H5a.5.5 0 0 1-.5-.5zm0-2A.5.5 0 0 1 5 6h6a.5.5 0 0 1 0 1H5a.5.5 0 0 1-.5-.5zm0-2A.5.5 0 0 1 5 4h6a.5.5 0 0 1 0 1H5a.5.5 0 0 1-.5-.5z"/>
                       </svg> @FileType.Csv
                    </button>
                    <button class="dropdown-item" type="submit" asp-page-handler="ExportExcel">
                        <svg style="margin-top: -3px; margin-right: 1px;" class="bi bi-file-spreadsheet" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M4 1h8a2 2 0 012 2v10a2 2 0 01-2 2H4a2 2 0 01-2-2V3a2 2 0 012-2zm0 1a1 1 0 00-1 1v10a1 1 0 001 1h8a1 1 0 001-1V3a1 1 0 00-1-1H4z" clip-rule="evenodd"/>
                            <path fill-rule="evenodd" d="M13 6H3V5h10v1zm0 3H3V8h10v1zm0 3H3v-1h10v1z" clip-rule="evenodd"/>
                            <path fill-rule="evenodd" d="M5 14V6h1v8H5zm4 0V6h1v8H9z" clip-rule="evenodd"/>
                        </svg> @FileType.Excel
                    </button>
                </div>
            </div>
        </div>
    </div>
        
    @if (Model.CreditApplications == null)
    {
        @await Html.PartialAsync("_Error")
    }
    else
    {
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th scope="col">Телефон</th>
                <th scope="col">ФИО клиента</th>
                <th scope="col">Статус заявки</th>
                <th scope="col">Дата создания</th>
                <th scope="col">Таймер</th>
            </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.CreditApplications)
                {
                    <tr class="@(item.Status.GetCssColorClass())" style="cursor: pointer" onclick="window.location='credit-applications/@(item.CreditApplicationId)'">
                        <td>@item.PhoneNumber</td>
                        <td>@item.LastName @item.FirstName @item.MiddleName</td>
                        <td>@item.Status.GetDescription()</td>
                        <td>@item.Date.ToDateAndTimeFormat()</td>
                        <td>@if (
                                    item.Status == CreditApplicationStatus.New || 
                                    item.Status == CreditApplicationStatus.InProgress || 
                                    item.Status == CreditApplicationStatus.UnableToContact || 
                                    item.Status == CreditApplicationStatus.NeedToCallBack || 
                                    item.Status == CreditApplicationStatus.TechnicalProblem
                                )
                            {
                                @((DateTime.Now - item.Date).ToString(@"hh\:mm\:ss"))
                            }</td>
                    </tr>
                }
            </tbody>
        </table>
        <div>
            <input type="hidden" id="pageNumber" name="pageNumber" value="@Model.PageNumber"/>
            @if (Model.CreditApplications.Count > 0)
            {
                <ul class="pagination pagination-sm">
                    <li class="page-item">
                        <button type="button" asp-page-handler="Search" class="btn page-link" disabled="@(Model.PreviousButtonEnabled ? null : "disabled")" onclick="beforeSubmit(@(Model.PageNumber - 1));">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </button>
                    </li>
                    @for (var i = 1; i <= Model.TotalPages; i++)
                    {
                        <li class="page-item @(i == Model.PageNumber ? "active" : "")">
                            <button type="button" asp-page-handler="Search" class="page-link" onclick="beforeSubmit(@i);">@i</button>
                        </li>
                    }
                    <li class="page-item">
                        <button type="button" asp-page-handler="Search" class="btn page-link" disabled="@(Model.NextButtonEnabled ? null : "disabled")" onclick="beforeSubmit(@(Model.PageNumber + 1));">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </button>
                    </li>
                </ul>
            }            
        </div>
    }
</form>

@section scripts
{
    <script>
         $('#statusSelect').multiselect({
            buttonClass: 'btn btn-light',
            buttonWidth: '100%',
            nonSelectedText: 'Статус',
            selectAllText: 'Все',
            includeSelectAllOption: true,
            numberDisplayed: 1,
            selectAllValue: 0,
            selectAllName: 'statuses'
         });
         
         $('#profileTypeSelect').multiselect({
            buttonClass: 'btn btn-light',
            buttonWidth: '100%',
            nonSelectedText: 'Анкета',
            selectAllText: 'Все',
            includeSelectAllOption: true,
            numberDisplayed: 1,
            selectAllValue: 0,
            selectAllName: 'profileTypes'
         });
         
         $('.form-group.date input').datepicker({
             autoclose: true,
             language: 'ru'
         });
         
           
        function beforeSubmit(pageNumber){
            $('#pageNumber').val(pageNumber);
            $("#filtersForm").submit()
        }
    </script>
}